Repository keva-dev/keva, pull requests merged in 2021-12, with the labels that each got.

#52 Hashes commands implement
  docs/src/guide/overview/commands.md
  protocol/src/main/java/dev/keva/protocol/resp/hashbytes/BytesKey.java
  protocol/src/main/java/dev/keva/protocol/resp/hashbytes/BytesValue.java
  server/src/main/java/dev/keva/server/command/impl/hash/HDel.java
  server/src/main/java/dev/keva/server/command/impl/hash/HExists.java
  server/src/main/java/dev/keva/server/command/impl/hash/HGet.java
  server/src/main/java/dev/keva/server/command/impl/hash/HGetAll.java
  server/src/main/java/dev/keva/server/command/impl/hash/HKeys.java
  server/src/main/java/dev/keva/server/command/impl/hash/HLen.java
  server/src/main/java/dev/keva/server/command/impl/hash/HSet.java
  server/src/main/java/dev/keva/server/command/impl/hash/HStrLen.java
  server/src/main/java/dev/keva/server/command/impl/hash/HVals.java
  server/src/test/java/dev/keva/server/core/AbstractServerTest.java
  store/build.gradle
  store/src/main/java/dev/keva/store/KevaDatabase.java
  store/src/main/java/dev/keva/store/impl/ChronicleMapImpl.java
  store/src/main/java/dev/keva/store/impl/HashMapImpl.java
Labels: enhancement

#54 Lists commands implement
  docs/src/guide/overview/commands.md
  server/src/main/java/dev/keva/server/command/impl/list/LIndex.java
  server/src/main/java/dev/keva/server/command/impl/list/LLen.java
  server/src/main/java/dev/keva/server/command/impl/list/LPop.java
  server/src/main/java/dev/keva/server/command/impl/list/LPush.java
  server/src/main/java/dev/keva/server/command/impl/list/LRange.java
  server/src/main/java/dev/keva/server/command/impl/list/LRem.java
  server/src/main/java/dev/keva/server/command/impl/list/LSet.java
  server/src/main/java/dev/keva/server/command/impl/list/RPop.java
  server/src/main/java/dev/keva/server/command/impl/list/RPush.java
  server/src/main/java/dev/keva/server/core/KevaServer.java
  server/src/main/java/dev/keva/server/core/Server.java
  server/src/test/java/dev/keva/server/core/AbstractServerTest.java
  server/src/test/java/dev/keva/server/core/KevaServerTest.java
  store/src/main/java/dev/keva/store/KevaDatabase.java
  store/src/main/java/dev/keva/store/impl/ChronicleMapImpl.java
  store/src/main/java/dev/keva/store/impl/HashMapImpl.java
Labels: enhancement

#53 Implement STRING commands
  docs/src/guide/overview/commands.md
  server/src/main/java/dev/keva/server/command/impl/string/GetSet.java
  server/src/main/java/dev/keva/server/command/impl/string/MGet.java
  server/src/main/java/dev/keva/server/command/impl/string/SetRange.java
  server/src/main/java/dev/keva/server/command/impl/string/Strlen.java
  server/src/test/java/dev/keva/server/core/AbstractServerTest.java
  store/src/main/java/dev/keva/store/KevaDatabase.java
  store/src/main/java/dev/keva/store/impl/OffHeapDatabaseImpl.java
  store/src/main/java/dev/keva/store/impl/OnHeapDatabaseImpl.java
Labels: enhancement

#62 Add Netty Native Transport loader
  server/build.gradle
  server/src/main/java/dev/keva/server/core/KevaServer.java
  server/src/main/java/dev/keva/server/core/NettyNativeLoader.java
Labels: enhancement

#61 Fix empty key not returning
  protocol/src/main/java/dev/keva/protocol/resp/reply/BulkReply.java
  server/src/test/java/dev/keva/server/core/AbstractServerTest.java
Labels: bug

#70 Support JDK8
  .github/workflows/build.yml
  config/src/main/java/com/keva/config/ConfigLoader.java
  config/src/test/java/com/keva/config/ArgsParserTest.java
  core/src/main/java/dev/keva/core/command/impl/key/Del.java
  core/src/main/java/dev/keva/core/command/impl/key/Exists.java
  core/src/main/java/dev/keva/core/command/impl/key/Expire.java
  core/src/main/java/dev/keva/core/command/impl/key/ExpireAt.java
  core/src/main/java/dev/keva/core/command/impl/key/Incrby.java
  core/src/main/java/dev/keva/core/command/impl/pubsub/Publish.java
  core/src/main/java/dev/keva/core/command/impl/pubsub/Subscribe.java
  core/src/main/java/dev/keva/core/command/impl/pubsub/Unsubscribe.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Discard.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Exec.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Multi.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Unwatch.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Watch.java
  core/src/main/java/dev/keva/core/command/impl/transaction/manager/TransactionContext.java
  core/src/main/java/dev/keva/core/server/KevaServer.java
  core/src/test/java/dev/keva/core/server/AbstractServerTest.java
  docs/src/guide/developer-guide.md
  docs/src/guide/overview/install.md
  store/src/main/java/dev/keva/store/impl/OffHeapDatabaseImpl.java
  store/src/main/java/dev/keva/store/impl/OnHeapDatabaseImpl.java
Labels: enhancement

#67 Add check AOF file writable
  core/src/main/java/dev/keva/core/aof/AOFContainer.java
Labels: bug

#76 Update docs
  README.md
  docs/src/guide/README.md
  docs/src/guide/insight/benchmark.md
  docs/src/guide/overview/install.md
  docs/src/guide/overview/replication.md
  docs/src/index.md
  docs/src/team/index.md
Labels: documentation

#72 Implements Netty Thread-local object pool for Command
  core/src/main/java/dev/keva/core/aof/AOFContainer.java
  core/src/main/java/dev/keva/core/command/impl/key/manager/ExpirationManager.java
  core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java
  resp-protocol/src/main/java/dev/keva/protocol/resp/Command.java
  resp-protocol/src/main/java/dev/keva/protocol/resp/RedisCommandDecoder.java
Labels: enhancement

#74 Fix string deserialize exception
  core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java
  core/src/test/java/dev/keva/core/server/AbstractServerTest.java
Labels: bug

#79 Implement ZAdd and Zscore
  core/src/main/java/dev/keva/core/aof/AOFContainer.java
  core/src/main/java/dev/keva/core/command/impl/zset/ZAdd.java
  core/src/main/java/dev/keva/core/command/impl/zset/ZScore.java
  core/src/test/java/dev/keva/core/server/AOFTest.java
  core/src/test/java/dev/keva/core/server/AbstractServerTest.java
  docs/src/guide/overview/commands.md
  resp-protocol/src/main/java/dev/keva/protocol/resp/reply/BulkReply.java
  resp-protocol/src/main/java/dev/keva/protocol/resp/reply/ErrorReply.java
  store/src/main/java/dev/keva/store/KevaDatabase.java
  store/src/main/java/dev/keva/store/impl/OffHeapDatabaseImpl.java
  store/src/main/java/dev/keva/store/impl/OnHeapDatabaseImpl.java
  store/src/main/java/dev/keva/store/type/ZSet.java
  util/src/main/java/dev/keva/util/Constants.java
  util/src/main/java/dev/keva/util/DoubleUtil.java
Labels: enhancement

#78 Implement string command DECR, DECRBY, GETRANGE
  core/src/main/java/dev/keva/core/command/impl/string/Decr.java
  core/src/main/java/dev/keva/core/command/impl/string/Decrby.java
  core/src/main/java/dev/keva/core/command/impl/string/GetRange.java
  core/src/main/java/dev/keva/core/command/impl/string/Incr.java
  core/src/main/java/dev/keva/core/command/impl/string/IncrByFloat.java
  core/src/main/java/dev/keva/core/command/impl/string/Incrby.java
  core/src/main/java/dev/keva/core/command/impl/string/MSet.java
  core/src/test/java/dev/keva/core/server/AbstractServerTest.java
  docs/src/guide/overview/commands.md
  store/src/main/java/dev/keva/store/KevaDatabase.java
  store/src/main/java/dev/keva/store/impl/OffHeapDatabaseImpl.java
  store/src/main/java/dev/keva/store/impl/OnHeapDatabaseImpl.java
Labels: enhancement

#82 Reboot Keva config
  config/src/main/java/com/keva/config/util/ArgsParser.java
  config/src/test/java/com/keva/config/ArgsParserTest.java
  config/src/test/java/com/keva/config/ConfigLoaderTest.java
  core/src/main/java/dev/keva/core/config/KevaConfig.java
  docs/src/guide/overview/install.md
Labels: documentation, enhancement

#86 Update docs
  docs/src/index.md
  docs/src/team/index.md
Labels: documentation

#88 Fix keva config
  config/src/main/java/com/keva/config/util/ArgsHolder.java
Labels: bug

#92 Fix AOF everysec bug
  core/src/main/java/dev/keva/core/aof/AOFContainer.java
  core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java
Labels: bug

#91 Use FileSystem sync for AOF
  core/src/main/java/dev/keva/core/aof/AOFContainer.java
  core/src/main/java/dev/keva/core/aof/AOFManager.java
  core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java
  core/src/test/java/dev/keva/core/server/AOFTest.java
Labels: enhancement

#94 Delombok var val
  app/src/main/java/dev/keva/app/Application.java
  config/src/main/java/com/keva/config/ConfigLoader.java
  config/src/main/java/com/keva/config/util/ArgsParser.java
  config/src/main/java/com/keva/config/util/ConfigLoaderUtil.java
  core/src/main/java/dev/keva/core/aof/AOFManager.java
  core/src/main/java/dev/keva/core/command/impl/hash/HDel.java
  core/src/main/java/dev/keva/core/command/impl/hash/HExists.java
  core/src/main/java/dev/keva/core/command/impl/hash/HGet.java
  core/src/main/java/dev/keva/core/command/impl/hash/HGetAll.java
  core/src/main/java/dev/keva/core/command/impl/hash/HKeys.java
  core/src/main/java/dev/keva/core/command/impl/hash/HLen.java
  core/src/main/java/dev/keva/core/command/impl/hash/HStrLen.java
  core/src/main/java/dev/keva/core/command/impl/hash/HVals.java
  core/src/main/java/dev/keva/core/command/impl/key/Dump.java
  core/src/main/java/dev/keva/core/command/impl/key/ExpireAt.java
  core/src/main/java/dev/keva/core/command/impl/key/Restore.java
  core/src/main/java/dev/keva/core/command/impl/key/Type.java
  core/src/main/java/dev/keva/core/command/impl/list/LIndex.java
  core/src/main/java/dev/keva/core/command/impl/list/LLen.java
  core/src/main/java/dev/keva/core/command/impl/list/LPop.java
  core/src/main/java/dev/keva/core/command/impl/list/LRange.java
  core/src/main/java/dev/keva/core/command/impl/list/RPop.java
  core/src/main/java/dev/keva/core/command/impl/pubsub/Publish.java
  core/src/main/java/dev/keva/core/command/impl/pubsub/Subscribe.java
  core/src/main/java/dev/keva/core/command/impl/pubsub/Unsubscribe.java
  core/src/main/java/dev/keva/core/command/impl/server/Info.java
  core/src/main/java/dev/keva/core/command/impl/string/Append.java
  core/src/main/java/dev/keva/core/command/impl/string/Decrby.java
  core/src/main/java/dev/keva/core/command/impl/string/GetDel.java
  core/src/main/java/dev/keva/core/command/impl/string/GetSet.java
  core/src/main/java/dev/keva/core/command/impl/string/IncrByFloat.java
  core/src/main/java/dev/keva/core/command/impl/string/Incrby.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Discard.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Exec.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Multi.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Unwatch.java
  core/src/main/java/dev/keva/core/command/impl/transaction/Watch.java
  core/src/main/java/dev/keva/core/command/impl/transaction/manager/TransactionContext.java
  core/src/main/java/dev/keva/core/command/impl/zset/ZAdd.java
  core/src/main/java/dev/keva/core/command/impl/zset/ZScore.java
  core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java
  core/src/main/java/dev/keva/core/config/DBConfig.java
  core/src/main/java/dev/keva/core/server/KevaServer.java
  core/src/main/java/dev/keva/core/server/NettyChannelHandler.java
  store/src/main/java/dev/keva/store/impl/OnHeapDatabaseImpl.java
Labels: enhancement

#97 refactor AOF exception handling
  core/src/main/java/dev/keva/core/aof/AOFContainer.java
  core/src/main/java/dev/keva/core/exception/StartupException.java
Labels: enhancement

#100 add back AppendOnlyObjectOutputStream to fix Stream corruption issue
  core/src/main/java/dev/keva/core/aof/AOFContainer.java
Labels: bug
